from __future__ import annotations

from django.apps import AppConfig


class NotificationsConfig(AppConfig):
    """Notifications — a thin per-user in-app inbox (docs/adr/0035).

    Rows are *references* to domain events, never copies of domain state. They
    are generated by the idempotent ``generate_notifications`` reminder scan
    (docs/adr/0005) and never carry sensitive figures (docs/adr/0009).
    """

    default_auto_field = "django.db.models.BigAutoField"
    name = "notifications"
    verbose_name = "الإشعارات"
