# Generated by Django 5.2.17 on 2026-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('conciliation', 'صلح'), ('first_instance', 'بداية'), ('appeal', 'استئناف'), ('cassation', 'نقض'), ('sharia', 'شرعية'), ('administrative', 'إدارية'), ('other', 'أخرى')], default='first_instance', max_length=30, verbose_name='النوع')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'محكمة',
                'verbose_name_plural': 'المحاكم',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='court_name_city_uniq')],
            },
        ),
    ]
