# Generated by Django 5.2.17 on 2026-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='court',
            name='department',
            field=models.CharField(blank=True, max_length=120, verbose_name='الدائرة'),
        ),
        migrations.AddField(
            model_name='court',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='court',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='الهاتف'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['name'], name='courts_cour_name_39e975_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['type'], name='courts_cour_type_fac21a_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['is_active'], name='courts_cour_is_acti_bc541b_idx'),
        ),
    ]
