# Generated by Django 5.2.17 on 2026-09-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_caseevent_hearing_types'),
        ('courts', '0002_court_full_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('scheduled_at', models.DateTimeField(verbose_name='موعد الجلسة')),
                ('hearing_type', models.CharField(choices=[('first_session', 'جلسة أولى'), ('pleading', 'مرافعة'), ('evidence', 'بيّنات'), ('deliberation', 'مداولة'), ('verdict', 'نطق بالحكم'), ('other', 'أخرى')], default='first_session', max_length=20, verbose_name='نوع الجلسة')),
                ('room', models.CharField(blank=True, max_length=60, verbose_name='القاعة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('held', 'تمت'), ('postponed', 'مؤجلة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('result', models.TextField(blank=True, verbose_name='النتيجة')),
                ('next_action', models.CharField(blank=True, max_length=250, verbose_name='الإجراء التالي')),
                ('next_hearing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الجلسة القادمة')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hearings', to='cases.case', verbose_name='القضية')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to='courts.court', verbose_name='المحكمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearings', to=settings.AUTH_USER_MODEL, verbose_name='المحامي الحاضر')),
                ('previous_hearing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='hearings.hearing', verbose_name='جلسة سابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ('-scheduled_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['case', '-scheduled_at'], name='hearings_he_case_id_8763c7_idx'), models.Index(fields=['status', 'scheduled_at'], name='hearings_he_status_da210e_idx'), models.Index(fields=['scheduled_at'], name='hearings_he_schedul_439bc4_idx'), models.Index(fields=['court'], name='hearings_he_court_i_28cad2_idx')],
            },
        ),
    ]
