# Generated by Django 5.2.17 on 2026-09-10 10:33

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0008_alter_caseevent_event_type'),
        ('clients', '0002_client_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='المرجع')),
                ('fee_type', models.CharField(choices=[('fixed', 'مقطوع'), ('hourly', 'بالساعة'), ('contingency', 'نسبة من المحصّل'), ('retainer', 'أتعاب دورية')], default='fixed', max_length=15, verbose_name='نوع الأتعاب')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ المقطوع')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='سعر الساعة')),
                ('contingency_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='النسبة %')),
                ('currency', models.CharField(choices=[('ILS', 'شيكل'), ('JOD', 'دينار أردني'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='ILS', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'سارية'), ('completed', 'منجزة'), ('cancelled', 'ملغاة')], default='draft', max_length=15, verbose_name='الحالة')),
                ('agreed_on', models.DateField(blank=True, null=True, verbose_name='تاريخ الاتفاق')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_agreements', to='cases.case', verbose_name='القضية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'اتفاقية أتعاب',
                'verbose_name_plural': 'اتفاقيات الأتعاب',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('unpaid', 'غير مدفوعة'), ('partially_paid', 'مدفوعة جزئيًا'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='draft', max_length=15, verbose_name='الحالة')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('currency', models.CharField(choices=[('ILS', 'شيكل'), ('JOD', 'دينار أردني'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='ILS', max_length=3, verbose_name='العملة')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الخصم')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='قيمة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='الإجمالي')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='المدفوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='الموكل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('fee_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.feeagreement', verbose_name='اتفاقية الأتعاب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('credit_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الإشعار الدائن')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('issued_on', models.DateField(default=datetime.date.today, verbose_name='تاريخ الإصدار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='finance.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'إشعار دائن',
                'verbose_name_plural': 'الإشعارات الدائنة',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('description', models.CharField(max_length=300, verbose_name='البند')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='إجمالي البند')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
                'ordering': ('position', 'pk'),
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='مرجع الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('paid_on', models.DateField(verbose_name='تاريخ الدفع')),
                ('method', models.CharField(choices=[('cash', 'نقدًا'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('other', 'أخرى')], default='cash', max_length=15, verbose_name='طريقة الدفع')),
                ('external_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع خارجي')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice', verbose_name='الفاتورة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ('-paid_on', '-created_at'),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('reversed_on', models.DateField(default=datetime.date.today, verbose_name='تاريخ الاسترجاع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.payment', verbose_name='الدفعة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'استرجاع دفعة',
                'verbose_name_plural': 'استرجاعات الدفعات',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='المرجع')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('ILS', 'شيكل'), ('JOD', 'دينار أردني'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='ILS', max_length=3, verbose_name='العملة')),
                ('category', models.CharField(choices=[('court_fees', 'رسوم محكمة'), ('government_fees', 'رسوم حكومية'), ('expert_fees', 'أتعاب خبراء'), ('travel', 'سفر وتنقّل'), ('office', 'مصاريف مكتب'), ('translation', 'ترجمة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('spent_on', models.DateField(verbose_name='تاريخ الصرف')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='clients.client', verbose_name='الموكل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ('-spent_on', '-created_at'),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx'), models.Index(fields=['case'], name='finance_exp_case_id_13eea8_idx'), models.Index(fields=['client'], name='finance_exp_client__75c813_idx'), models.Index(fields=['-spent_on'], name='finance_exp_spent_o_149fb7_idx'), models.Index(fields=['deleted_at'], name='finance_exp_deleted_a47a92_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['status'], name='finance_fee_status_b42d08_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['fee_type'], name='finance_fee_fee_typ_bb26dd_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['case'], name='finance_fee_case_id_8d524a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeagreement',
            index=models.Index(fields=['-created_at'], name='finance_fee_created_688514_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeagreement',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gte', 0), _connector='OR'), name='fee_fixed_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='feeagreement',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__isnull', True), ('hourly_rate__gte', 0), _connector='OR'), name='fee_hourly_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='feeagreement',
            constraint=models.CheckConstraint(condition=models.Q(('contingency_percent__isnull', True), models.Q(('contingency_percent__gte', 0), ('contingency_percent__lte', 100)), _connector='OR'), name='fee_contingency_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='feeagreement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='fee_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='finance_inv_client__37a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['case'], name='finance_inv_case_id_17c65f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='finance_inv_due_dat_b93853_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='finance_inv_created_cfd7c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='invoice_tax_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_tax_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='invoice_amount_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('total'))), name='invoice_no_overpayment'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['invoice'], name='finance_cre_invoice_517121_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_note_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='line_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='finance_pay_invoice_122c17_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-paid_on'], name='finance_pay_paid_on_eb3945_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentreversal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reversal_amount_positive'),
        ),
    ]
