# Generated by Django 5.2.17 on 2026-09-08 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_search_indexes'),
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'نوع قضية',
                'verbose_name_plural': 'أنواع القضايا',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('case_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم القضية')),
                ('internal_reference', models.CharField(blank=True, max_length=60, verbose_name='مرجع داخلي')),
                ('court_case_number', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='رقم القضية لدى المحكمة')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='الدائرة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المتابعة'), ('in_trial', 'قيد المحاكمة'), ('on_hold', 'معلقة'), ('concluded', 'منتهية'), ('closed', 'مغلقة')], default='new', max_length=20, verbose_name='الحالة')),
                ('stage', models.CharField(blank=True, max_length=120, verbose_name='المرحلة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='قيمة المطالبة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('assigned_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_cases', to=settings.AUTH_USER_MODEL, verbose_name='المحامي المسؤول')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client', verbose_name='الموكل')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courts.court', verbose_name='المحكمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'القضايا',
                'ordering': ('-created_at',),
                'permissions': [('view_confidential_case', 'عرض الملاحظات القانونية والداخلية للقضية')],
            },
        ),
        migrations.CreateModel(
            name='CaseConfidential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_notes', models.TextField(blank=True, verbose_name='ملاحظات قانونية')),
                ('internal_notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidential', to='cases.case')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملاحظات سرية للقضية',
                'verbose_name_plural': 'ملاحظات سرية للقضايا',
            },
        ),
        migrations.CreateModel(
            name='CaseLawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_links', to='cases.case')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='supporting_lawyers',
            field=models.ManyToManyField(blank=True, related_name='supporting_cases', through='cases.CaseLawyer', through_fields=('case', 'lawyer'), to=settings.AUTH_USER_MODEL, verbose_name='محامون مساندون'),
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('kind', models.CharField(choices=[('general', 'ملاحظة'), ('correspondence', 'مراسلة')], default='general', max_length=20, verbose_name='النوع')),
                ('body', models.TextField(verbose_name='النص')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
            ],
            options={
                'verbose_name': 'ملاحظة قضية',
                'verbose_name_plural': 'ملاحظات القضايا',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_role', models.CharField(choices=[('client', 'عميل'), ('opponent', 'طرف مقابل'), ('counsel', 'محامٍ'), ('representative', 'ممثل'), ('other', 'جهة أخرى')], default='opponent', max_length=20, verbose_name='الصفة')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='cases.case')),
                ('linked_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_party_links', to='clients.client', verbose_name='عميل مرتبط')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طرف',
                'verbose_name_plural': 'الأطراف',
                'ordering': ('party_role', 'name'),
            },
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casetype', verbose_name='النوع'),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'إنشاء القضية'), ('updated', 'تعديل بيانات القضية'), ('status_changed', 'تغيير الحالة'), ('lawyer_assigned', 'إسناد المحامي المسؤول'), ('lawyer_added', 'إضافة محامٍ مساند'), ('lawyer_removed', 'إزالة محامٍ مساند'), ('party_added', 'إضافة طرف'), ('party_removed', 'إزالة طرف'), ('note_added', 'إضافة ملاحظة'), ('closed', 'إغلاق القضية'), ('reopened', 'إعادة فتح القضية')], max_length=30)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'verbose_name': 'حدث في الخط الزمني',
                'verbose_name_plural': 'أحداث الخط الزمني',
                'ordering': ('-occurred_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['case', '-occurred_at'], name='cases_casee_case_id_6cb4bd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='caselawyer',
            constraint=models.UniqueConstraint(fields=('case', 'lawyer'), name='caselawyer_uniq'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['type'], name='cases_case_type_id_3245d8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client'], name='cases_case_client__c6764b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_lawyer'], name='cases_case_assigne_e47633_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='cases_case_created_a2f158_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['filing_date'], name='cases_case_filing__d5a33e_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.CheckConstraint(condition=models.Q(('claim_amount__isnull', True), ('claim_amount__gte', 0), _connector='OR'), name='case_claim_amount_non_negative'),
        ),
    ]
