# Generated by Django 5.2.17 on 2026-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'إنشاء القضية'), ('updated', 'تعديل بيانات القضية'), ('status_changed', 'تغيير الحالة'), ('lawyer_assigned', 'إسناد المحامي المسؤول'), ('lawyer_added', 'إضافة محامٍ مساند'), ('lawyer_removed', 'إزالة محامٍ مساند'), ('party_added', 'إضافة طرف'), ('party_removed', 'إزالة طرف'), ('note_added', 'إضافة ملاحظة'), ('closed', 'إغلاق القضية'), ('reopened', 'إعادة فتح القضية'), ('hearing_scheduled', 'جدولة جلسة'), ('hearing_updated', 'تعديل بيانات جلسة'), ('hearing_rescheduled', 'إعادة جدولة جلسة'), ('hearing_held', 'عقد جلسة'), ('hearing_postponed', 'تأجيل جلسة'), ('hearing_cancelled', 'إلغاء جلسة')], max_length=30),
        ),
    ]
