# Generated by Django 5.2.17 on 2026-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caseevent_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'إنشاء القضية'), ('updated', 'تعديل بيانات القضية'), ('status_changed', 'تغيير الحالة'), ('lawyer_assigned', 'إسناد المحامي المسؤول'), ('lawyer_added', 'إضافة محامٍ مساند'), ('lawyer_removed', 'إزالة محامٍ مساند'), ('party_added', 'إضافة طرف'), ('party_removed', 'إزالة طرف'), ('note_added', 'إضافة ملاحظة'), ('closed', 'إغلاق القضية'), ('reopened', 'إعادة فتح القضية'), ('hearing_scheduled', 'جدولة جلسة'), ('hearing_updated', 'تعديل بيانات جلسة'), ('hearing_rescheduled', 'إعادة جدولة جلسة'), ('hearing_held', 'عقد جلسة'), ('hearing_postponed', 'تأجيل جلسة'), ('hearing_cancelled', 'إلغاء جلسة'), ('task_added', 'إضافة مهمة'), ('task_status_changed', 'تغيير حالة مهمة'), ('task_removed', 'حذف مهمة'), ('deadline_added', 'إضافة موعد نهائي'), ('deadline_status_changed', 'تغيير حالة موعد نهائي'), ('document_added', 'إضافة مستند'), ('document_removed', 'سحب مستند'), ('contract_added', 'إضافة عقد'), ('contract_status_changed', 'تغيير حالة عقد')], max_length=30),
        ),
    ]
