# Generated by Django 5.2.17 on 2026-09-10 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0007_alter_caseevent_event_type'),
        ('clients', '0002_client_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم العقد')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('contract_type', models.CharField(choices=[('retainer', 'اتفاقية أتعاب دورية'), ('engagement', 'اتفاقية تمثيل قانوني'), ('services', 'عقد خدمات'), ('consulting', 'عقد استشارات'), ('lease', 'عقد إيجار'), ('employment', 'عقد عمل'), ('nda', 'اتفاقية سرية'), ('settlement', 'اتفاقية تسوية'), ('other', 'أخرى')], default='engagement', max_length=20, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='القيمة')),
                ('currency', models.CharField(choices=[('ILS', 'شيكل'), ('JOD', 'دينار أردني'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو')], default='ILS', max_length=3, verbose_name='العملة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'ساري'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], default='draft', max_length=15, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='الموكل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'), models.Index(fields=['contract_type'], name='contracts_c_contrac_fe5845_idx'), models.Index(fields=['end_date'], name='contracts_c_end_dat_dedd36_idx'), models.Index(fields=['client'], name='contracts_c_client__6ebd28_idx'), models.Index(fields=['case'], name='contracts_c_case_id_05a69c_idx'), models.Index(fields=['-created_at'], name='contracts_c_created_fb92fc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__isnull', True), ('value__gte', 0), _connector='OR'), name='contract_value_non_negative'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_after_start')],
            },
        ),
    ]
