# Generated by Django 5.2.17 on 2026-09-08 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('client_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='رقم العميل')),
                ('type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], max_length=20, verbose_name='النوع')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم الكامل')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('national_id', models.CharField(blank=True, max_length=30, verbose_name='رقم الهوية')),
                ('registration_number', models.CharField(blank=True, max_length=40, verbose_name='رقم التسجيل التجاري')),
                ('phone', models.CharField(max_length=30, verbose_name='الهاتف')),
                ('secondary_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف إضافي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='المدينة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('prospect', 'عميل محتمل'), ('archived', 'مؤرشف')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ('company_name', 'full_name', 'client_number'),
                'permissions': [('view_sensitive_client', 'عرض بيانات العميل الحساسة (رقم الهوية)')],
                'indexes': [models.Index(fields=['client_number'], name='clients_cli_client__d84143_idx'), models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'), models.Index(fields=['status'], name='clients_cli_status_ce0d15_idx'), models.Index(fields=['type'], name='clients_cli_type_2216d9_idx'), models.Index(fields=['-created_at'], name='clients_cli_created_552574_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type', 'individual'), models.Q(('full_name', ''), _negated=True)), models.Q(('type', 'company'), models.Q(('company_name', ''), _negated=True)), _connector='OR'), name='client_name_matches_type')],
            },
        ),
    ]
