# Generated by Django 5.2.17 on 2026-09-09 10:30

import django.db.models.deletion
import documents.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0006_caseevent_document_types'),
        ('clients', '0002_client_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('name', models.CharField(max_length=250, verbose_name='الاسم')),
                ('document_type', models.CharField(choices=[('pleading', 'لوائح ومذكرات'), ('contract', 'عقد'), ('power_of_attorney', 'وكالة'), ('judgment', 'حكم أو قرار'), ('evidence', 'بيّنة'), ('correspondence', 'مراسلة'), ('official', 'وثيقة رسمية'), ('identity', 'وثيقة هوية'), ('financial', 'مستند مالي'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='النوع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(max_length=255, storage=documents.storage.document_storage, upload_to=documents.storage.document_upload_path, verbose_name='الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='نوع المحتوى')),
                ('size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='الحجم')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='بصمة SHA-256')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.client', verbose_name='الموكل')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='رفعه')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['case'], name='documents_d_case_id_528e86_idx'), models.Index(fields=['client'], name='documents_d_client__75b1a2_idx'), models.Index(fields=['deleted_at'], name='documents_d_deleted_135b7b_idx'), models.Index(fields=['sha256'], name='documents_d_sha256_e75cfc_idx')],
            },
        ),
    ]
