# Generated by Django 5.2.17 on 2026-09-10 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_caseevent_event_type'),
        ('clients', '0002_client_search_indexes'),
        ('contracts', '0001_initial'),
        ('documents', '0002_document_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contracts.contract', verbose_name='العقد'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['contract'], name='documents_d_contrac_918d6a_idx'),
        ),
    ]
