# Generated by Django 5.2.17 on 2026-09-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='الإجراء')),
                ('entity_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف الكيان')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='وصف الكيان')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='وكيل المستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='حدث في')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='الفاعل')),
            ],
            options={
                'verbose_name': 'حدث تدقيق',
                'verbose_name_plural': 'أحداث التدقيق',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
