# Generated by Django 5.2.17 on 2026-09-09 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0005_caseevent_task_types'),
        ('clients', '0002_client_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='التاريخ النهائي')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('met', 'مستوفى'), ('missed', 'فائت'), ('cancelled', 'ملغى')], default='pending', max_length=15, verbose_name='الحالة')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='سُجّل في')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='clients.client', verbose_name='الموكل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'موعد نهائي',
                'verbose_name_plural': 'المواعيد النهائية',
                'ordering': ('due_date',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['status'], name='tasks_deadl_status_3d9476_idx'), models.Index(fields=['due_date'], name='tasks_deadl_due_dat_1b7d93_idx'), models.Index(fields=['case'], name='tasks_deadl_case_id_046efc_idx'), models.Index(fields=['client'], name='tasks_deadl_client__b1e13e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('done', 'مكتملة'), ('cancelled', 'ملغاة')], default='new', max_length=15, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='اكتملت في')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='مُسندة إلى')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cases.case', verbose_name='القضية')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client', verbose_name='الموكل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'), models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'), models.Index(fields=['assigned_to'], name='tasks_task_assigne_ab55af_idx'), models.Index(fields=['case'], name='tasks_task_case_id_29e236_idx'), models.Index(fields=['client'], name='tasks_task_client__30685e_idx'), models.Index(fields=['deleted_at'], name='tasks_task_deleted_fed458_idx')],
            },
        ),
    ]
