# Generated by Django 5.2.17 on 2026-09-10 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حُدّث في')),
                ('category', models.CharField(choices=[('hearing_upcoming', 'جلسة قادمة'), ('task_overdue', 'مهمة متأخرة'), ('deadline_approaching', 'موعد نهائي يقترب'), ('invoice_overdue', 'فاتورة متأخرة السداد'), ('contract_expiring', 'عقد قريب من الانتهاء')], max_length=32, verbose_name='الفئة')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('body', models.CharField(max_length=500, verbose_name='النص')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='الرابط')),
                ('entity_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف الكيان')),
                ('dedupe_key', models.CharField(max_length=200, verbose_name='مفتاح إزالة التكرار')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='قُرئ في')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['category'], name='notificatio_categor_fd561f_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='uniq_notification_recipient_dedupe')],
            },
        ),
    ]
